[package]
name = "teo-py"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "teo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.2"
teo = { path = "../teo" }
pyo3-asyncio = { version = "0.20.0", features = ["attributes", "tokio-runtime"] }
tokio = { version = "1.0" }
to-mut = { version = "0.1.0" }
bigdecimal = "0.3.0"
chrono = { version = "0.4.24" }
