[package]
name = "teo-py"
version = "0.0.43"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "teo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
teo = { path = "../teo", features = ["data-source-mysql", "data-source-postgres", "data-source-sqlite", "data-source-mongodb"] }
pyo3-asyncio = { version = "0.18", features = ["attributes", "tokio-runtime"] }
tokio = "1.26"
to-mut = { version = "0.1.0" }
